# Windows-specific wrapper around vcpkg toolchain.
# Probes common locations so the file works without VCPKG_ROOT being set.
if(NOT DEFINED VCPKG_ROOT)
    if(DEFINED ENV{VCPKG_ROOT})
        set(VCPKG_ROOT "$ENV{VCPKG_ROOT}")
    else()
        # VS-bundled vcpkg (Visual Studio 2022 / 2025 Insiders)
        foreach(_vs_ver 18 17)
            foreach(_vs_edition "Insiders" "Enterprise" "Professional" "Community" "BuildTools")
                set(_candidate "C:/Program Files/Microsoft Visual Studio/${_vs_ver}/${_vs_edition}/VC/vcpkg")
                if(EXISTS "${_candidate}/scripts/buildsystems/vcpkg.cmake")
                    set(VCPKG_ROOT "${_candidate}")
                    break()
                endif()
            endforeach()
            if(DEFINED VCPKG_ROOT)
                break()
            endif()
        endforeach()
        # Standalone vcpkg fallbacks
        if(NOT DEFINED VCPKG_ROOT)
            foreach(_fallback "C:/vcpkg" "$ENV{USERPROFILE}/vcpkg" "C:/tools/vcpkg")
                if(EXISTS "${_fallback}/scripts/buildsystems/vcpkg.cmake")
                    set(VCPKG_ROOT "${_fallback}")
                    break()
                endif()
            endforeach()
        endif()
    endif()
endif()

if(NOT DEFINED VCPKG_TARGET_TRIPLET)
    set(VCPKG_TARGET_TRIPLET "x64-windows")
endif()

set(_VCPKG_TOOLCHAIN "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
if(NOT EXISTS "${_VCPKG_TOOLCHAIN}")
    message(FATAL_ERROR "Cannot find vcpkg toolchain at ${_VCPKG_TOOLCHAIN}. Set VCPKG_ROOT.")
endif()

include("${_VCPKG_TOOLCHAIN}")
